#
# Executes commands at the start of an interactive session.
#

# Exports that must load before Prezto
export NVM_LAZY_LOAD=true

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Apple commands
alias nogate='xattr -rd com.apple.quarantine'

# Folder commands
alias c!='cd ~/Code'
alias d!='cd ~/Code/Dotfiles'
alias j!='cd ~/Code/JavaScript'
alias l!='cd ~/Code/Laravel'
alias s!='cd ~/Code/Swift'
alias w!='cd ~/Code/Work'

# File Commands
alias hidden='ls -a | grep "^\."'

# ZSH / Prezto commands
alias de!='code ~/Code/Dotfiles/install.conf.yaml'
alias di!='sh ~/Code/Dotfiles/install'
alias p!='code ~/.zpreztorc'
alias r!='source ~/.zshrc'
alias z!='code ~/.zshrc'
alias zp!='code ~/.zpreztorc'

alias ctop='docker run --rm -ti \
  --name=ctop \
  -v /var/run/docker.sock:/var/run/docker.sock \
  quay.io/vektorlab/ctop:latest'

alias dcud='docker-compose up -d'
alias dcd='docker-compose down'

# Brew commands
alias bup!='brew update && brew upgrade'
alias cup!='brew cask upgrade --greedy'
alias bd!='brew bundle dump --global --force'
alias bf!='code ~/.Brewfile'

alias dmg='hdiutil attach'
alias dfimage='docker run -v /var/run/docker.sock:/var/run/docker.sock --rm chenzj/dfimage'

function gi() { curl -sLw "\n" https://www.gitignore.io/api/$@ ;}

# Git commands


# Add Golang modules to PATH
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# Add Composer packages to PATH
export PATH=$PATH:$HOME/.composer/vendor/bin

# Add Ruby packages to PATH
export PATH="$PATH:$HOME/.rvm/bin"

# Add Python packages to PATH
export PATH="$PATH:$HOME/.env/bin"

# Add LaTeX packages to PATH
export PATH="$PATH:/usr/local/texlive/2020/bin/x86_64-darwin"

# Add custom package to PATH
export PATH="$PATH:$HOME/.bin"

# Luarocks path stuff
export LUA_PATH='/usr/local/Cellar/luarocks/3.7.0/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/lib/lua/5.1/?.lua;/usr/local/lib/lua/5.1/?/init.lua;./?.lua;./?/init.lua;/Users/mario/.luarocks/share/lua/5.1/?.lua;/Users/mario/.luarocks/share/lua/5.1/?/init.lua'
export LUA_CPATH='/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so;./?.so;/Users/mario/.luarocks/lib/lua/5.1/?.so'
export PATH="$PATH:~/.luarocks/bin"
