#
# Executes commands at the start of an interactive session.
#

# Exports that must load before Prezto
export NVM_LAZY_LOAD=true

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Folder commands
alias c!='cd ~/Code'
alias d!='cd ~/Code/Dotfiles'
alias j!='cd ~/Code/JavaScript'
alias l!='cd ~/Code/Laravel'
alias s!='cd ~/Code/Swift'

# ZSH / Prezto commands
alias de!='code ~/Code/Dotfiles/install.conf.yaml'
alias di!='sh ~/Code/Dotfiles/install'
alias p!='code ~/.zpreztorc'
alias r!='source ~/.zshrc'
alias z!='code ~/.zshrc'
alias zp!='code ~/.zpreztorc'

alias ctop='docker run --rm -ti \
  --name=ctop \
  -v /var/run/docker.sock:/var/run/docker.sock \
  quay.io/vektorlab/ctop:latest'

alias dcud='docker-compose up -d'
alias dcd='docker-compose down'

# Brew commands
alias bup!='brew update && brew upgrade && brew cask upgrade --greedy'
alias cup!='brew cask upgrade --greedy'
alias bd!='brew bundle dump --global --force'
alias bf!='code ~/.Brewfile'

alias dmg='hdiutil attach'

function gi() { curl -sLw "\n" https://www.gitignore.io/api/$@ ;}

# Git commands


# Add Composer packages to PATH
export PATH=~/.composer/vendor/bin:$PATH

# Add Ruby packages to PATH
export PATH="$PATH:$HOME/.rvm/bin"

# Add Python packages to PATH
export PATH="$PATH:$HOME/.env/bin"
